load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

def chart_repo(
    name = "",
    remote = "",
    commit = "",
    shallow_since = "",
    path_prefix = "",
    charts = [],
    replacements = {},
    inner_deps = {},
    ignore_files = {},
    ):

    deps_bzl = """cat <<EOT >> deps.bzl
load("@com_github_tomsons_rules_helm//:workspace.bzl", "rules_helm_dependencies")

def load_charts():
"""
    for chart in charts:
        chart_name = chart
        ignore = ""
        if chart in ignore_files.keys():
            ignore = ignore_files[chart]
        if chart in replacements.keys():
            chart_name = replacements[chart]
        deps_bzl += """
    rules_helm_dependencies(
        name = "{chart_name}",
        repository = "{repository}",
        chart_path = "{chart_path}",
        ignore_files = "{ignore}",
    )
""".format(
    chart_name = chart_name,
    repository = name,
    chart_path = chart,
    ignore = ignore,
    )

    deps_bzl += "EOT"

    new_git_repository(
        name = name,
        remote = remote,
        commit = commit,
        shallow_since = shallow_since,
        strip_prefix = path_prefix,
        patch_cmds = [
            deps_bzl,
        ],
        build_file_content = "# Generated by rules_helm",
    )